name: eShop Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./eShopOnWeb.sln
    - name: Build
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Test
      run: dotnet test ./eShopOnWeb.sln --configuration Release
      
  buildPushAppImage:
    needs: build
    name: Build and Push to ACR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.ACR_USER_rt}} 
        # Container registry password
        password: ${{ secrets.ACR_PASSWORD_rt}}
        # Container registry server url
        login-server: ${{ secrets.ACR_SECRET_rt}}
    - run: |
        docker build -f src/Web/Dockerfile . - t ${{ secrets.ACR_SECRET_rt}}/eshop:{{ github.run_id }}
        docker push ${{ secrets.ACR_SECRET_rt}}/eshop:{{ github.run_id }}
